### ISSUE TITLE
Redis server crashed after building and loading redistimeseries module

### ISSUE THREAD

**Issue by averias** [RedisTimeSeries/RedisTimeSeries#294] opened 2020-01-05 12:13 UTC
OS= Ubuntu 18.04 x64
Redis server version = 4.0.11 

I followed the steps indicated in https://oss.redislabs.com/redistimeseries/#build-and-run-it-yourself and after generating `redistimeseries.so` and adding it as module, redis-server crashed when it is restarted. Looking at the redis server logs I got:

10138:C 05 Jan 11:35:25.138 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
10138:C 05 Jan 11:35:25.138 # Redis version=4.0.11, bits=64, commit=00000000, modified=0, pid=10138, just started
10138:C 05 Jan 11:35:25.138 # Configuration loaded
10138:C 05 Jan 11:35:25.138 # systemd supervision requested, but NOTIFY_SOCKET not found

Running in standalone mode
Redis 4.0.11 (00000000/0) 64 bit
Port: 6379
PID: 10155
                                           

10155:M 05 Jan 11:35:25.140 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
10155:M 05 Jan 11:35:25.140 # Server initialized
10155:M 05 Jan 11:35:25.140 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
10155:M 05 Jan 11:35:25.140 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
10155:M 05 Jan 11:35:25.141 # <ReJSON> JSON data type for Redis v99.99.99 [encver 0]
10155:M 05 Jan 11:35:25.141 * Module 'ReJSON' loaded from /etc/redis/rejson.so
10155:M 05 Jan 11:35:25.141 * Module 'bf' loaded from /etc/redis/redisbloom.so

=== REDIS BUG REPORT START: Cut & paste starting from here ===
10155:M 05 Jan 11:35:25.141 # Redis 4.0.11 crashed by signal: 11
10155:M 05 Jan 11:35:25.141 # Accessing address: (nil)
10155:M 05 Jan 11:35:25.141 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
/usr/bin/redis-server 127.0.0.1:6379(logStackTrace+0x45)[0x5640a523f755]
/usr/bin/redis-server 127.0.0.1:6379(sigsegvHandler+0xb1)[0x5640a523ff01]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12dd0)[0x7fef8b178dd0]

------ INFO OUTPUT ------
# Server
redis_version:4.0.11
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:fc908f68b3e66abd
redis_mode:standalone
os:Linux 4.18.0-25-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:8.2.0
process_id:10155
run_id:acb39acd3c58a56651759ee35b6aacd7762422d0
tcp_port:6379
uptime_in_seconds:0
uptime_in_days:0
hz:10
lru_clock:1162221
executable:/usr/bin/redis-server
config_file:/etc/redis/redis.conf

# Clients
connected_clients:0
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:808424
used_memory_human:789.48K
used_memory_rss:0
used_memory_rss_human:0B
used_memory_peak:808424
used_memory_peak_human:789.48K
used_memory_peak_perc:inf%
used_memory_overhead:791008
used_memory_startup:791008
used_memory_dataset:17416
used_memory_dataset_perc:100.00%
total_system_memory:16710840320
total_system_memory_human:15.56G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:0.00
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1578220525
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:0
total_commands_processed:0
instantaneous_ops_per_sec:0
total_net_input_bytes:0
total_net_output_bytes:0
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:436867a3040b049ffbc52045bb28af24a487c699
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.00
used_cpu_user:0.00
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Commandstats

# Cluster
cluster_enabled:0

# Keyspace

------ CLIENT LIST OUTPUT ------

------ REGISTERS ------
10155:M 05 Jan 11:35:25.148 # 
RAX:00007fef8adb0758 RBX:00007fef8adb09e8
RCX:00007fef80000000 RDX:00007fef8adb0bd0
RDI:0000000000000000 RSI:00007fef8add1848
RBP:00007ffea03b3700 RSP:00007ffea03b3668
R8 :00007fef8b4236ac R9 :00007fef8add17b8
R10:00007fef8add1770 R11:00007fef8b211b00
R12:00007fef8adb0a50 R13:00007fef8adb0710
R14:00007fef8a8d6168 R15:0000000000000000
RIP:0000000000000000 EFL:0000000000010246
CSGSFS:002b000000000033
10155:M 05 Jan 11:35:25.148 # (00007ffea03b3677) -> 0000000000000000
10155:M 05 Jan 11:35:25.148 # (00007ffea03b3676) -> 00007fef8a8d6168
10155:M 05 Jan 11:35:25.148 # (00007ffea03b3675) -> 00007fef8a8bc621
10155:M 05 Jan 11:35:25.148 # (00007ffea03b3674) -> 00007fef8a87d300
10155:M 05 Jan 11:35:25.148 # (00007ffea03b3673) -> 00005640a526c355
10155:M 05 Jan 11:35:25.148 # (00007ffea03b3672) -> 0fb3f4867eec7800
10155:M 05 Jan 11:35:25.148 # (00007ffea03b3671) -> 00007fef8ada7580
10155:M 05 Jan 11:35:25.148 # (00007ffea03b3670) -> 0000000000000000
10155:M 05 Jan 11:35:25.148 # (00007ffea03b366f) -> 00007fef8ada7720
10155:M 05 Jan 11:35:25.148 # (00007ffea03b366e) -> 00007fef8ada8e00
10155:M 05 Jan 11:35:25.148 # (00007ffea03b366d) -> 00007fef8ada7130
10155:M 05 Jan 11:35:25.148 # (00007ffea03b366c) -> 00007fef8ada6ea0
10155:M 05 Jan 11:35:25.148 # (00007ffea03b366b) -> 0000000000000001
10155:M 05 Jan 11:35:25.148 # (00007ffea03b366a) -> 00007fef8ada68b2
10155:M 05 Jan 11:35:25.148 # (00007ffea03b3669) -> 00007fef8a8d6168
10155:M 05 Jan 11:35:25.148 # (00007ffea03b3668) -> 00007fef8ada269f

------ FAST MEMORY TEST ------
10155:M 05 Jan 11:35:25.148 # Bio thread for job type #0 terminated
10155:M 05 Jan 11:35:25.148 # Bio thread for job type #1 terminated
10155:M 05 Jan 11:35:25.148 # Bio thread for job type #2 terminated
*** Preparing to test memory region 5640a52dc000 (90112 bytes)
*** Preparing to test memory region 7fef87e23000 (8388608 bytes)
*** Preparing to test memory region 7fef88624000 (8388608 bytes)
*** Preparing to test memory region 7fef88e25000 (8388608 bytes)
*** Preparing to test memory region 7fef8a400000 (8388608 bytes)
*** Preparing to test memory region 7fef8adcf000 (24576 bytes)
*** Preparing to test memory region 7fef8adef000 (8192 bytes)
*** Preparing to test memory region 7fef8af78000 (16384 bytes)
*** Preparing to test memory region 7fef8b162000 (16384 bytes)
*** Preparing to test memory region 7fef8b183000 (16384 bytes)
*** Preparing to test memory region 7fef8b424000 (2228224 bytes)
*** Preparing to test memory region 7fef8b7d7000 (8192 bytes)
*** Preparing to test memory region 7fef8b819000 (4096 bytes)
.O.O.O.O.O.O.O.O.O.O.O.O.O
Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

=== REDIS BUG REPORT END. Make sure to include from START to END. ===

       Please report the crash by opening an issue on github:

           http://github.com/antirez/redis/issues

  Suspect RAM error? Use redis-server --test-memory to verify it.

**I also tested memory and all is ok:**

Your memory passed this test.
Please if you are still in doubt use the following two tools:
1) memtest86: http://www.memtest86.com/
2) memtester: http://pyropus.ca/software/memtester/

As you can see I have also installed `reJson` and `redisBloom` modules in my instance of redis server and they are working properly, so I disabled them to load just `redistimeseries` module to see if the issue is related to, but it's still crashing.

**The output when I built `redistimeseries`module:**

~/RedisTimeSeries$ sudo make setup

apt-get -qq update -y
/usr/bin/python2 -m pip --version
pip 19.3.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
pip install --disable-pip-version-check wheel
pip install --disable-pip-version-check setuptools --upgrade
apt-get -qq install -y git jq curl
apt-get -qq install -y build-essential
apt-get -qq install -y lcov
pip install --disable-pip-version-check -r tests/requirements.txt

~/RedisTimeSeries$ sudo make build
make[1]: Entering directory '/home/bewater/RedisTimeSeries/src'
Makefile:105: warning: overriding recipe for target 'clean'
../deps/readies/mk/build.rules:12: warning: ignoring old recipe for target 'clean'
Compiling chunk.c...
Compiling compaction.c...
Compiling compressed_chunk.c...
Compiling config.c...
Compiling generic_chunk.c...
Compiling gorilla.c...
Compiling indexer.c...
Compiling module.c...
Compiling parse_policies.c...
Compiling tsdb.c...
Compiling rdb.c...
Building rmutil...
In file included from compaction.h:10,
                 from tsdb.h:10,
                 from module.c:17:
module.c: In function ‘parseLabelsFromArgs’:
consts.h:56:4: warning: ISO C forbids braced-groups within expressions [-Wpedantic]
    ({ __typeof__ (a) _a = (a); \
    ^
module.c:41:29: note: in expansion of macro ‘max’
     *label_count = (size_t)(max(0, (argc - first_label_pos) / 2 ));
                             ^~~
module.c: In function ‘ReplySeriesRange’:
consts.h:56:4: warning: ISO C forbids braced-groups within expressions [-Wpedantic]
    ({ __typeof__ (a) _a = (a); \
    ^
module.c:517:8: note: in expansion of macro ‘max’
        max(start_ts, series->lastTimestamp - series->retentionTime) : start_ts;
        ^~~
Makefile:40: warning: overriding recipe for target 'clean'
../../deps/readies/mk/build.rules:12: warning: ignoring old recipe for target 'clean'
Compiling ../../deps/RedisModulesSDK/rmutil/util.c...
Compiling ../../deps/RedisModulesSDK/rmutil/strings.c...
Compiling ../../deps/RedisModulesSDK/rmutil/sds.c...
Compiling ../../deps/RedisModulesSDK/rmutil/vector.c...
Compiling ../../deps/RedisModulesSDK/rmutil/alloc.c...
Compiling ../../deps/RedisModulesSDK/rmutil/periodic.c...
Creating ../../bin/linux-x64-release/rmutil/librmutil.a...
Linking ../bin/linux-x64-release/redistimeseries.so...
make[1]: Leaving directory '/home/bewater/RedisTimeSeries/src'

I noticed a similar issue posted in your repository that was solved by upgrading from version 4.x to 5.x here https://github.com/RedisTimeSeries/RedisTimeSeries/issues/226, but before upgrading my redis server to version 5 can you please confirm if `redistimeseries` module can be installed with redis version 4.x or I'm doing something wrong?

Thanks in advance

**Comment by ashtul** [comment] 2020-01-05 12:43
@averias It could be the fact you are using Redis 4.0

ping @rafie

**Comment by ashtul** [comment] 2020-02-02 15:54
This was caused by a bug that was fixed in PR #310

**Closed by ashtul** 2020-02-02 15:54 UTC
