### ISSUE TITLE
Will RedisTimeSeries support string values?

### ISSUE THREAD

**Issue by william-zong** [RedisTimeSeries/RedisTimeSeries#1629] opened 2024-09-05 03:26 UTC
We can just add 64-bit floating-point values into RedisTimeSeries now, sometimes, I need to add string values or other values.

So, will RedisTimeSeries support string values?

**Comment by LiorKogan** [comment] 2024-09-05 05:02
Duplicate of #740

**Closed by LiorKogan** 2024-09-05 05:02 UTC
