### ISSUE TITLE
Redis Opensource as a backend database in our microservice for production deployment

### ISSUE THREAD

**Issue by SurKanchi** [RedisTimeSeries/RedisTimeSeries#1125] opened 2022-04-12 17:21 UTC
I need simple answer whether can i use redis community edition opensource as a backend database in our microservice for production deployment. 
I have a confusion after reading this "If your application built with RSAL-protected software is NOT a database product, RSAL defines it as “your application,”

**Comment by LiorKogan** [comment] 2022-04-12 18:21
Closed as duplicate of #1126

**Closed by LiorKogan** 2022-04-12 18:21 UTC
Labels: duplicate
