### ISSUE TITLE
about Rax

### ISSUE THREAD

**Issue by chtt66** [RedisTimeSeries/RedisTimeSeries#284] opened 2019-12-24 11:03 UTC
hi，the document indicates that the redistimeseries uses the rax data structure that is same as stream. What is the function of this structure (range query based on timestamp?) Which file is reflected in the source code?

**Comment by danni-m** [comment] 2019-12-24 11:08
Hi @chtt66,
Thanks for being interested in our project.

The best place for this type of conversations would be our mailing list at https://groups.google.com/forum/#!forum/redistimeseries, the issues sections are oriented around bugs and features.

To answer your question, it is used for finding out which chunks contained in a specific time range.
You can see in `tsdb.c` where its being used as the holding datastrcture of all the chunks, heres the initialization of the RAX:
```
    newSeries->chunks = RedisModule_CreateDict(NULL);
```

**Comment by danni-m** [comment] 2019-12-24 11:08
Im closing this as it is not a bug, @chtt66 you are welcome to comment and continue the discussion.

**Closed by danni-m** 2019-12-24 11:08 UTC

**Comment by chtt66** [comment] 2019-12-24 11:16
Thanks for answering
