### ISSUE TITLE
32-bit ARMv6 support? redistimeseries.so failed to load: undefined symbol: __aeabi_uldivmod

### ISSUE THREAD

**Issue by theronic** [RedisTimeSeries/RedisTimeSeries#67] opened 2019-03-18 11:30 UTC
I compiled redistimeseries.so and redis-server on a Raspberry Pi Zero W. When I try to load the module from the redis-cli, I get an error that seems to pertain to 32-bit vs 64-bit systems:

```
7122:M 18 Mar 2019 11:27:33.168 * Ready to accept connections
7122:M 18 Mar 2019 11:27:43.690 # Module redistimeseries.so failed to load: redistimeseries.so: cannot open shared object file: No such file or directory
7122:M 18 Mar 2019 11:27:56.734 # Module /home/pi/redistimeseries.so failed to load: /home/pi/redistimeseries.so: undefined symbol: __aeabi_uldivmod

```

I know Redis supports 32-bit, but does RedisTimeSeries?

**Comment by gkorland** [comment] 2019-03-18 12:17
https://stackoverflow.com/questions/25623956/aeabi-ldivmod-undefined-when-compiling-kernel-module

**Comment by markusr** [comment] 2019-03-21 17:23
I don't think that this is a 32-bit problem. I tested it on a Raspberry Pi 3B. 
it compiles, loads and runs payload without problems. 

It think the problem is that Raspberry Pi Zero W is ARMv6 and Raspberry Pi 3B is ARMv7.

@theronic 
Which gcc did you use?

**Comment by theronic** [comment] 2019-03-26 06:54
@markusr:

```
$ gcc --version
gcc (Raspbian 6.3.0-18+rpi1+deb9u1) 6.3.0 20170516
```

Any idea how to get past this issue?

**Comment by markusr** [comment] 2019-03-26 09:53
I have the same gcc version on Raspberry Pi 3B, so we can rule this out.

Please try adding 
```
-mfloat-abi=soft
```

to the ```CFLAGS``` in the Makefile.

If this fails try some values for ```-march```,  see [GCC ARM options](https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html).

**Comment by danni-m** [comment] 2019-03-26 16:46
@theronic I have an extra raspberrypi laying somewhere, I might be able to look into this in 2 weeks.

**Comment by K-Jo** [comment] 2019-03-26 17:39
@andresrinivasan

**Comment by theronic** [comment] 2019-03-27 08:21
@markusr when I modify the line in Makefile to:

    CFLAGS = -I$(RM_INCLUDE_DIR) -Wall -O3 -g -fPIC -lc -lm -std=gnu99 -mfloat-abi=soft  -DREDIS_MODULE_TARGET -DREDISMODULE_EXPERIMENTAL_API

I get error " fatal error: gnu/stubs-soft.h: No such file or directory":

```
~/RedisTimeSeries/src $ make all
make -C ../RedisModulesSDK/rmutil
make[1]: Entering directory '/home/pi/RedisTimeSeries/RedisModulesSDK/rmutil'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/RedisTimeSeries/RedisModulesSDK/rmutil'
cc -I../RedisModulesSDK -Wall -O3 -g -fPIC -lc -lm -std=gnu99 -mfloat-abi=soft  -DREDIS_MODULE_TARGET -DREDISMODULE_EXPERIMENTAL_API   -c -o module.o module.c
In file included from /usr/include/features.h:388:0,
                 from /usr/include/time.h:27,
                 from module.c:6:
/usr/include/arm-linux-gnueabihf/gnu/stubs.h:7:29: fatal error: gnu/stubs-soft.h: No such file or directory
 # include <gnu/stubs-soft.h>
                             ^
compilation terminated.
<builtin>: recipe for target 'module.o' failed
make: *** [module.o] Error 1
```

**Comment by theronic** [comment] 2019-03-27 08:23
Also tried with `-march=armv6zk` on same line. No dice.

**Comment by theronic** [comment] 2019-03-27 08:25
@markusr when I run, `dpkg --print-architecture`, I get armhf, so it's running a hard float architecture, and wouldn't expect soft float to work.

**Comment by theronic** [comment] 2019-03-27 08:31
Perhaps [this patch](https://github.com/DynamoRIO/dynamorio/commit/6e5529a27aadac634ee1f1cc7ea1f211aef74ce3) to another library is relevant to get these symbols defined?

**Comment by theronic** [comment] 2019-04-27 14:27
Any idea how to fix this? I'm blocked on using RedisTimeSeries on a Pi Zero for some IoT monitoring. Reluctantly have to coax InfluxDB not too suck memory dry.

**Comment by itamarhaber** [comment] 2019-04-27 20:01
Referring this to our resident ARM expert @rafie

**Comment by danni-m** [comment] 2019-04-29 09:23
I need access to a RPi Zero, @itamarhaber do we have one in the office maybe?

**Comment by itamarhaber** [comment] 2019-04-29 13:24
Yes - @gkorland has at least 3.14 of these.

**Comment by rafie** [comment] 2019-05-02 13:00
I'm running a QEMUlated stretch Raspbian with 4.14 kernel. Built Redis & TS with native ARM gcc 6.3.
I got the module loaded. It crashed upon the very first TS.CREATE command, in what might be a memory alignment issue.
Investigation continues.

**Comment by theronic** [comment] 2019-05-31 15:18
@antirez wrote about [unaligned memory issues](http://antirez.com/news/111) on the Raspberry Pi. Perhaps the same applies to RedisTimeSeries?

**Comment by rafie** [comment] 2019-08-20 10:57
As we concluded it's not a link problem (but rather, most probably, memory alignment one), we're closing this.

**Closed by rafie** 2019-08-20 10:57 UTC
Labels: enhancement
