### ISSUE TITLE
How to query a range by count?

### ISSUE THREAD

**Issue by rudmac** [RedisTimeSeries/RedisTimeSeries#141] opened 2019-06-18 19:15 UTC
Hello,

1) Is it possible to get the last N events time from a key instead of using time range?

2) Also, is it possible to set a trim to a time series by certain number of entries instead seconds?

If not, could be a future feature?

Thanks!

**Comment by gkorland** [comment] 2019-06-18 20:56
@rudmac no, currently it only supports time range.
Can you please extend on your use case/need?

**Comment by K-Jo** [comment] 2019-06-19 08:25
@rudmac there is TS.GET and TS.MGET to get the last value. (N=1)  We have considered having an optional parameter there to specify the number of samples you want to retrieve.

**Comment by rudmac** [comment] 2019-06-19 15:12
@gkorland When working with financial market and in my case with pair trading algo with a lot of linear regression calcs, we have for eg.: all close day history price inside redis, and we do pair close price lr calcs with 250, 200, 150, 100 days history, but we don't know the exactly timestamp of Nst day to retrieve the data from redis, financial markets have some especific calendar. I my case I just wanna the last 200 days of data, and so on... Now I'm retrieving all the info from 0  to -1 and slicing the list to fit the needs, wasting a little of processing and memory.

@K-Jo It would be awesome. Looking forward to use this.

Cheers,

**Comment by gkorland** [comment] 2019-07-02 10:20
```
TS.RANGE key fromTimestamp toTimestamp [AGGREGATION aggregationType timeBucket] [COUNT count]
```

**Comment by K-Jo** [comment] 2019-07-02 12:33
@gkorland why not on GET / MGET?

**Comment by gkorland** [comment] 2019-07-02 20:02
@K-Jo we need both the issue is that having TS.RANGE without count is a risk to get too many results.
Once we add support for COUNT the user will be able to paginate the result

**Comment by ashtul** [comment] 2019-07-03 03:50
@gkorland , while true for range, for mrange the user might get different time ranges for any of the series and then iterating is impossible.

**Comment by gkorland** [comment] 2019-07-03 06:04
Right MRANGE seems a bit trickier, perhaps we need to extend MRANGE to get timestamp per key

**Comment by ashtul** [comment] 2019-07-03 07:12
On the other hand, users will probably use it with aggregation and therefore the number of results would be almost identical.
Simple parsing on client side will allow them to decide from which timestamp to start next iteration

**Comment by ashtul** [comment] 2019-07-03 07:12
PR #163

**Comment by lyrixx** [comment] 2019-07-29 16:52
I have a similar requirements. I store some metrics in redis and when I want to display them, I want to get only X (60) data points. So I use  `AGGREGATION avg Y`. So I need to compute Y.
To do so, I need the very first (A) point and the last one (B). Then, I will be able to compute Y (`(B - A) / X`.
Or maybe there is another solution to achieve that? 

Of course, I can use some data I store somewhere else to compute A, But It would be better to be able to compute everything with this datastructure.

Or it could be nice to add A to `TS.INFO` ?! 

OR It could be nice to let redis compute such calcul by itself ?
```
TS.RANGE key fromTimestamp toTimestamp [AGGREGATION aggregationType timeBucket] [MAX 60] 
```
In my case:
```
TS.RANGE key - + AGGREGATION avg default MAX 60
```

WDYT?

**Comment by ashtul** [comment] 2019-08-17 18:14
@lyrixx you should create a rule that will save a sample every 60 ms, then you can query it in O(1) since the calculation was already done for you.
`TS.CREATERULE sourceKey destKey AGGREGATION avg 60`

**Comment by lyrixx** [comment] 2019-08-19 08:54
Thanks @ashtul for your reply. 

I think I didn't explain my use case well enough, because your reply does not solve my issue. 
I don't want a data point each 60ms, but I always want 60 (or less) data points, whatever the period. I want that, because I display data as a chart, and it's useless to grab thousand of data points.

**Comment by ashtul** [comment] 2019-08-19 11:21
@lyrixx Sorry but I got confused with the aggregation.
We've actually just merged a [COUNT count] flag for both TS.RANGE and TS.MRANGE so you can query the exact number of samples you need and then process them on your side,

**Comment by lyrixx** [comment] 2019-08-20 13:33
Nice :+1: It looks like it's in 1.0.2 release?
I will test this on Thursday.

**Comment by ashtul** [comment] 2019-08-26 14:52
#163 and #180

**Closed by ashtul** 2019-08-26 14:52 UTC
Labels: enhancement
