### ISSUE TITLE
Cannot build on macOS

### ISSUE THREAD

**Issue by VividVisions** [RedisTimeSeries/RedisTimeSeries#558] opened 2020-10-22 18:27 UTC
I've tried building this module on macOS 10.14.6 but it fails on many fronts.
First, I encountered the error mentioned in #498.
Then, if I (kinda) fix that and run `make setup` as ordinary user, it fails with this error:

> Error: An unexpected error occurred during the `brew link` step
> Error: Permission denied @ dir_s_mkdir - /usr/local/Frameworks

If I run it with sudo, Homebrew refuses to work because it should and can not be run as root (see [Homebrew FAQ](https://docs.brew.sh/FAQ#why-does-homebrew-say-sudo-is-bad)) but apparently, the setup/install script needs to be run as root. So I guess, this has to be done in separate steps.

Is there a step-by-step documentation on how to build RedisTimeSeries on macOS?

**Comment by rafie** [comment] 2020-10-22 20:33
@VividVisions I suspect there's something wrong with your `/usr/local` permissions. This can be caused by forcing `brew` to run with `sudo` (or as `root`), making it create files and dirs under `/usr/local` with `root` ownership, which later will prevent `brew` from accessing them when run as a regular user.
The above problem can be fixed by running `sudo chown -R $USER /usr/local`, but please handle it carefully as this advice is related to macOS system administration and has nothing to do with RedisTimeSeries.
As for build instructions, they can be found at https://oss.redislabs.com/redistimeseries/development (there are no specific macOS instructions, except for avoiding `sudo` in the installation process). However, the above page contains some errors (which we will promptly fix), so please use the following steps:
```
git submodule update --init --recursive
PIP=1 ./deps/readies/bin/getpy2
./system-setup.py
make
make test
```

**Comment by VividVisions** [comment] 2020-10-22 22:51
@rafie Thank you so much for your quick reply! I should've figured this out by myself but it was a long day. After fixing the rights of `/usr/local/Frameworks` and other Homebrew related directories, it worked following the steps you posted.

And I had to symlink `/usr/bin/python` to `/usr/local/bin/python2`. An alias didn't suffice.

Now I get this when starting the Redis server with loadmodule:
```
<timeseries> RedisTimeSeries version 999999, git_sha=f091cc7f4bd352c55e135524764c4be437a85d9d
<timeseries> Redis version found by RedisTimeSeries : 6.0.8 - oss
 Module 'timeseries' loaded from /usr/local/RedisTimeSeries/bin/redistimeseries.so
```
(Is version 999999 a bug?) 

Thanks again!

**Comment by gkorland** [comment] 2020-10-24 05:33
No it's not a bug, it indicates you're using code straight from master branch, please notice the official versions are tagged on git.

**Comment by danni-m** [comment] 2020-11-04 08:14
@VividVisions this seem to be resolved, im closing this issue, if you still have issues with the build please reopen.

**Closed by danni-m** 2020-11-04 08:14 UTC
Labels: help wanted
